// framework/vue/src/components/Controls.vue
<template>
	<div class="controls">
		<a href="#" class="button" @click.prevent="togglePlay">{{playButtonText}}</a> 
		<a href="#" class="button" @click.prevent="clearPattern">Clear</a> 
		<Slider :bpm="bpm" @changeBpm="changeBpm" />
	</div>
</template>

<script>
	import Slider from './Slider.vue';

	export default {
		props: ['playing', 'bpm'],
		components: { Slider },
		computed: {
			playButtonText() {
				return (this.playing) ? 'Stop' : 'Play';
			}
		},
		methods: {
			togglePlay() {
				this.$emit('togglePlay');
			},
			clearPattern() {
				this.$emit('clearPattern');
			},
			changeBpm(bpm) {
				this.$emit('changeBpm', bpm);
			}
		}
	}
</script>

// framework/angular/src/app/controls/controls.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'controls',
  templateUrl: './controls.component.html',
})
export class ControlsComponent {

	@Input() bpm: number;
	@Input() playing: boolean;

	@Output() togglePlay: EventEmitter<any> = new EventEmitter<any>();
	@Output() clearPattern: EventEmitter<any> = new EventEmitter<any>();
	@Output() updateBpm: EventEmitter<any> = new EventEmitter<any>();

	toggle(): void {
		this.togglePlay.emit();
	}

	clear(): void {
		this.clearPattern.emit();
	}

	changeBpm(bpm: number): void {
		this.updateBpm.emit(bpm);
	}

}

<div class="controls">
	<a href="#" class="button" (click)="toggle()">{{ playing ? 'Stop': 'Play' }}</a> 
	<a href="#" class="button" (click)="clear()">Clear</a> 
	<div class="bpmRange">
		<div class="bpmTitle">BPM</div><input type="range" id="bpm" min="1" max="420" step="1" #ref (change)="changeBpm(ref.value)" /><output for="bpm" class="bpmOutput">{{ bpm }}</output>
	</div>
</div>
