// framework/angular/src/app/app.component.ts
import { Component, OnInit, AfterContentChecked } from '@angular/core';
import { StavesService } from './staves.service';
import { Stave } from './stave';
import '../styles.css';
declare const Howl:any;

@Component({
  selector: 'app-root',
  template: `
	<div class="machine">
		<div id="staves">
			<staves></staves>
			<transport [pos]="transportPos"></transport>
			<controls [bpm]="bpm" [playing]="playing" (togglePlay)="togglePlay($event)" (clearPattern)="clearPattern($event)" (updateBpm)="updateBpm($event)"></controls>
		</div>
	</div>
  `,
  providers: [StavesService]
})

export class AppComponent implements OnInit, AfterContentChecked {

	constructor(private stavesService: StavesService) {}

	transportPos: number = 0;
	playing: boolean = false;
	bpm: number = 220;	
	timerId: any;
	staves: Stave[];

	getStaves(): void {
		this.staves = this.stavesService.getStaves();
	}

	ngOnInit(): void {
		this.getStaves();
		for (var stave of this.staves) {
			let localStorageRef = localStorage.getItem('ag-pattern-' + stave.id);
			if (localStorageRef) {
				stave.notes = JSON.parse(localStorageRef);
			}
		}
	}

	ngAfterContentChecked(): void {
		for (var stave of this.staves) {
			localStorage.setItem('ag-pattern-' + stave.id, JSON.stringify(stave.notes));
		}
	}

	setTimer(): void {
		this.timerId = setInterval(() => this.tick(), this.calculateTempo(this.bpm));
	}

	tick(): void {
		this.transportPos++;
		if (this.transportPos > 7) {
			this.transportPos = 0;
		}
		this.checkNote();
	}

	checkNote(): void {
		for (var stave of this.staves) {
			for (var note of stave.notes) {
				if (note.active && note.pos === this.transportPos) {
					this.playSample(stave.sample);
				}
			}
		}
	}

	playSample(sample: string): void {
		let sound = new Howl({
			src: [sample]
		});
		sound.play();
	}

	calculateTempo(bpm: number): number {
		return 60000 / bpm;
	}

	togglePlay() {
		this.playing = !this.playing;
		if (this.playing) {
			this.setTimer();
		} else {
			clearInterval(this.timerId);
		}
	}

	clearPattern() {
		for (var stave of this.staves) {
			for (var note of stave.notes) {
				note.active = false;
			}
		}
	}

	updateBpm(bpm: number) {
		this.bpm = bpm;	
		if (this.playing) {
			clearInterval(this.timerId);
			this.setTimer();
		}
	}
}

<div class="machine">
  <div id="staves">
    <staves></staves>
    <transport [pos]="transportPos"></transport>
    <controls [bpm]="bpm" [playing]="playing" (togglePlay)="togglePlay($event)" (clearPattern)="clearPattern($event)" (updateBpm)="updateBpm($event)"></controls>
  </div>
</div>

// framework/vue/src/App.vue
<template>
	<div>
		<h1>DRU<strong>MVC</strong> - Vue</h1>
		<div class="machine">
			<div id="staves">
				<component v-for="stave in store.staves" :key="stave.id" is="stave" :name="stave.name" :notes="stave.notes" @toggleNote="toggleNote"></component>
				<Transport :pos="store.transportPos"></Transport>
				<Controls @togglePlay="togglePlay" @clearPattern="clearPattern"  @changeBpm="changeBpm" :playing="store.playing" :bpm="store.bpm"></Controls>
			</div>
		</div>
	</div>
</template>

<script>
	import store from './components/store.js';
	import Controls from './components/Controls.vue';
	import Stave from './components/Stave.vue';
	import Transport from './components/Transport.vue';

	export default {
		name: 'app',

		components: { Controls, Stave, Transport },

		data() { 
			return {
				store: store
			}
		},

		created() {
			this.restorePatterns();
			if (store.playing) {
				this.setTempo();
			}
		},

		methods: {
			setTempo() {
				this.timerId = setInterval(() => this.tick(), this.calculateTempo(store.bpm));
			},
			tick() {
				let transportPos = store.transportPos;
				transportPos++;
				if (transportPos > 7) {
					transportPos = 0;
				}
				store.transportPos = transportPos;
				this.checkNote();
			},
			calculateTempo(bpm) {
				return 60000 / bpm;
			},
			changeBpm(bpm) {
				store.bpm = bpm;
				if (store.playing) {
					clearInterval(this.timerId);
					this.setTempo();
				}
			},
			toggleNote(note) {
				note.active = !note.active;
				this.savePatterns();
			},
			checkNote() {
				let transportPos = store.transportPos;
				let that = this;
				for (var stave of store.staves) {
					for (var note of stave.notes) {
						if (note.active && note.pos === transportPos) {
							that.playSample(stave.sample);
						}
					}
				}
			},
			playSample(sample) {
				let sound = new Howl({
					src: [sample]
				});
				sound.play();
			},
			togglePlay() {
				if (store.playing) {
					clearInterval(this.timerId);
					store.playing = false;
				} else {
					this.setTempo();
					store.playing = true;
				}
			},
			clearPattern() {
				let staves = store.staves;
				for (var stave of staves) {
					for (var note of stave.notes) {
						note.active = false;
					}
				}
				store.staves = staves;
				this.savePatterns();
			},
			savePatterns() {
				for (var stave of store.staves) {
					localStorage.setItem('vb-pattern-' + stave.id, JSON.stringify(stave.notes));
				}				
			},
			restorePatterns() {
				for (var stave of store.staves) {
					let localStorageRef = localStorage.getItem('vb-pattern-' + stave.id);
					if (localStorageRef) {
						stave.notes = JSON.parse(localStorageRef);
					}
				}
			}
		}
	}
</script>
