// framework/vue/src/components/Slider.vue
<template>
	<div class="bpmRange">
		<div class="bpmTitle">BPM</div>
		<input type="range" id="bpm" min="1" max="420" step="1" v-model="rangeValue" @change="changeBpm" />
		<output htmlFor="bpm" class="bpmOutput">{{ rangeValue }}</output>
	</div>
</template>

<script>
export default {
	props: ['bpm'],
	data() {
		return {
			rangeValue: this.bpm
		}
	},
	methods: {
		changeBpm() {
			this.$emit('changeBpm', this.rangeValue);
		}
	}
}
</script>

// framework/react-redux/src/components/Slider.js
import React from "react";
import PropTypes from "prop-types";

const Slider = ({ bpm, handleChange }) => (
  <div className="bpmRange">
    <div className="bpmTitle">BPM</div>
    <input
      type="range"
      id="bpm"
      min="1"
      max="420"
      step="1"
      defaultValue={bpm}
      onChange={handleChange}
    />
    <output htmlFor="bpm" className="bpmOutput">
      {bpm}
    </output>
  </div>
);

Slider.propTypes = {
  bpm: PropTypes.string.isRequired,
  handleChange: PropTypes.func.isRequired
};

export default Slider;
