// framework/vue/src/components/Stave.vue
<template>
	<div class="stave">
		<div class="staveName">{{ name }}</div>
		<component v-for="note in notes" :id="note.id" :key="note.id" is="note" :active="note.active" @noteClick="toggleNote(note)"></component>
	</div>
</template>

<script>
import Note from './Note.vue';

export default {
	props: ['name', 'notes'],
	components: { Note },
	methods: {
		toggleNote(note) {
			this.$emit('toggleNote', note);
		}
	}
}
</script>

// framework/react-redux/src/components/Stave.js
import React from "react";
import PropTypes from "prop-types";
import Note from "./Note";

const Stave = ({ name, notes, id, transportPos, toggleActive }) => (
  <div className="stave">
    <div className="staveName">{name}</div>
    {notes.map((note, index) => 
        <Note
          key={index}
          stave={id}
          transportPos={transportPos}
          pos={note.pos}
          active={note.active}
          toggleActive={toggleActive}
        />
      )}
  </div>
);

Stave.propTypes = {
  id: PropTypes.number.isRequired,
  toggleActive: PropTypes.func.isRequired,
  transportPos: PropTypes.number.isRequired,
  name: PropTypes.string.isRequired,
  notes: PropTypes.arrayOf(
    PropTypes.shape({
      pos: PropTypes.number.isRequired,
      active: PropTypes.bool.isRequired
    })
  ).isRequired
};

export default Stave;
