// framework/vue/src/components/Transport.vue
<template>
	<div class="transportContainer">
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<div class="transport">
			<div class="transportLight transportLightActive" :style="lightPos"></div>
		</div>
	</div>
</template>

<script>
import TransportBlank from './TransportBlank.vue';

export default {
	props: ['pos'],
	components: { TransportBlank },
	computed: {
		lightPos() {
			return 'left:' + this.pos * 95 + 'px';
		}
	}
}
</script>

// framework/react-redux/src/components/Transport.js
import React from "react";
import PropTypes from "prop-types";
import TransportBlank from "./TransportBlank";

const Transport = props => (
  <div className="transportContainer">
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <TransportBlank />
    <div className="transport">
      <div
        className="transportLight transportLightActive"
        style={{ left: props.pos * 95 + "px" }}
      />
    </div>
  </div>
);

Transport.propTypes = {
  pos: PropTypes.number.isRequired
};

export default Transport;
