// framework/react-redux/src/components/Controls.js
import React from 'react';
import PropTypes from 'prop-types';
import Slider from './Slider';

const Controls = (props) => {
	const playButtonText = props.playing ? 'Stop' : 'Play';
	return (
		<div className="controls">
			<a href="#" className="button" onClick={props.togglePlay}>{playButtonText}</a> 
			<a href="#" className="button" onClick={props.clearPattern}>Clear</a> 
			<Slider bpm={props.bpm} handleChange={(e) => props.handleChange(e.target.value)}/>
		</div>
	)
}

Controls.propTypes = {
	bpm: PropTypes.number.isRequired,
	handleChange: PropTypes.func.isRequired,
	togglePlay: PropTypes.func.isRequired,
	playing: PropTypes.bool.isRequired,
	clearPattern: PropTypes.func.isRequired
}

export default Controls;

// framework/vue/src/components/Controls.vue
<template>
	<div class="controls">
		<a href="#" class="button" @click.prevent="togglePlay">{{playButtonText}}</a> 
		<a href="#" class="button" @click.prevent="clearPattern">Clear</a> 
		<Slider :bpm="bpm" @changeBpm="changeBpm" />
	</div>
</template>

<script>
	import Slider from './Slider.vue';

	export default {
		props: ['playing', 'bpm'],
		components: { Slider },
		computed: {
			playButtonText() {
				return (this.playing) ? 'Stop' : 'Play';
			}
		},
		methods: {
			togglePlay() {
				this.$emit('togglePlay');
			},
			clearPattern() {
				this.$emit('clearPattern');
			},
			changeBpm(bpm) {
				this.$emit('changeBpm', bpm);
			}
		}
	}
</script>
