// framework/react/src/components/Slider.js
import React from 'react';
import PropTypes from 'prop-types';

const Slider = (props) => (
	<div className="bpmRange">
		<div className="bpmTitle">BPM</div>
		<input type="range" id="bpm" min="1" max="420" step="1" defaultValue={props.bpm} onChange={props.handleChange} />
		<output htmlFor="bpm" className="bpmOutput">{ props.bpm }</output>
	</div>
)

Slider.propTypes = {
	bpm: PropTypes.number.isRequired,
	handleChange: PropTypes.func.isRequired
}

export default Slider;

// framework/vue/src/components/Slider.vue
<template>
	<div class="bpmRange">
		<div class="bpmTitle">BPM</div>
		<input type="range" id="bpm" min="1" max="420" step="1" v-model="rangeValue" @change="changeBpm" />
		<output htmlFor="bpm" class="bpmOutput">{{ rangeValue }}</output>
	</div>
</template>

<script>
export default {
	props: ['bpm'],
	data() {
		return {
			rangeValue: this.bpm
		}
	},
	methods: {
		changeBpm() {
			this.$emit('changeBpm', this.rangeValue);
		}
	}
}
</script>
