// framework/angular/src/app/stave/stave.component.ts
import { Component, Input } from "@angular/core";
import { Note } from "../note";

@Component({
  selector: "stave",
  templateUrl: "./stave.component.html"
})
export class StaveComponent {
  @Input() name: string;
  @Input() notes: Note[];

  onClick(note: Note): void {
    note.active = !note.active;
  }
}

<div class="stave">
  <div class="staveName">{{ name }}</div>
  <note *ngFor="let note of notes" (click)="onClick(note)" [active]="note.active"></note>
</div>

// framework/vue/src/components/Stave.vue
<template>
	<div class="stave">
		<div class="staveName">{{ name }}</div>
		<component v-for="note in notes" :id="note.id" :key="note.id" is="note" :active="note.active" @noteClick="toggleNote(note)"></component>
	</div>
</template>

<script>
import Note from './Note.vue';

export default {
	props: ['name', 'notes'],
	components: { Note },
	methods: {
		toggleNote(note) {
			this.$emit('toggleNote', note);
		}
	}
}
</script>
