// framework/angular/src/app/transport.component.ts
import { Component, Input } from '@angular/core';

@Component({
	selector: 'transport',
	template: `
		<div class="transportContainer">
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<transport-blank></transport-blank>
			<div class="transport">					
				<div class="transportLight transportLightActive" [ngStyle]="{left: pos * 95 + 'px'}"></div>
			</div>
		</div>	
	`
})

export class TransportComponent {
	@Input() pos: number;
}

// framework/vue/src/components/Transport.vue
<template>
	<div class="transportContainer">
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<TransportBlank/>
		<div class="transport">
			<div class="transportLight transportLightActive" :style="lightPos"></div>
		</div>
	</div>
</template>

<script>
import TransportBlank from './TransportBlank.vue';

export default {
	props: ['pos'],
	components: { TransportBlank },
	computed: {
		lightPos() {
			return 'left:' + this.pos * 95 + 'px';
		}
	}
}
</script>
